### PR TITLE
gcode_macro: Enable jinja2.ext.do extension

### PR DESCRIPTION
**Pull request by bwnance**
original PR: https://github.com/Klipper3d/klipper/pull/5149

@r3Fuze please let us know if you are against having your changes merged into danger-klipper!

### CODE REVIEW

**Comment by r3Fuze** [comment]
I don't mind 👍

**Comment by chestwood96** [comment]
Should that not be at least mentioned in the documentation somewhere? Maybe even with the nice little danger marker if/once that gets approved?

While I don't know what exactly that extension does I am pretty sure it would cause makros not to be directly portable to regular klipper.

**Comment by bwnance** [comment]
@chestwood96 it just adds support for a new `do` keyword to make statements clearer. Does not drop support for "do-less" statements, so no breaking changes.

**Comment by bwnance** [comment]
I will add a section to the macro commands templates doc though

**Review by rogerlz — APPROVED** [review]

**Review by rogerlz — APPROVED** [review]

**Pull request merged**
