### PR TITLE
Dans98 klipper velocity pid

### PR DESCRIPTION
**Pull request by bwnance**
upstream PR: https://github.com/Klipper3d/klipper/pull/6272

### CODE REVIEW

**Review by rogerlz — APPROVED** [review]

**Comment by dans98** [comment]
@bwnance  do you want me to directly submit a pr here for fixing the calibration code?

I'm pretty much done with upstream at this point.

**Comment by bwnance** [comment]
@dans98 that would be awesome :)

**Comment by dans98** [comment]
@bwnance i'm working on converting over to dangerklipper but i hit an error that makes no sense to me.

https://github.com/DangerKlippers/danger-klipper/issues/49

**Comment by dans98** [comment]
@bwnance 

I will have a pr ready tonight or tomorrow for the updates for pid_calibration, do we need to follow this commit format/policy here?
https://dangerklippers.github.io/danger-klipper/CONTRIBUTING.html#format-of-commit-messages

**Comment by bwnance** [comment]
@dans98 ah, we should update that. We've been pretty lax with it, so don't worry about it :)

**Comment by dans98** [comment]
@bwnance It's been submitted, sorry it took so long!
https://github.com/DangerKlippers/danger-klipper/pull/62

**Comment by dzid26** [comment]
This convoluted way of limiting the integral term.
You would have achieved the same by explicitly subtracting the remainder after the PWM saturation from the integral memory.

**Comment by dans98** [comment]
> This convoluted way of limiting the integral term. You would have achieved the same by explicitly subtracting the remainder after the PWM saturation from the integral memory.

The velocity algorithm is pretty much a standard in the motion control industry.

you can see an example of it derived here.
https://www.youtube.com/watch?v=vHHOlJMac4c

**Comment by dzid26** [comment]
> The velocity algorithm is pretty much a standard in the motion control industry.

Indeed this originates from motor control where second derivative of the desired position corresponds directly to commanded torque (or current) and thus useful.


Statements that this PID form is more susceptible to noise is wrong as the integration at the [end](https://github.com/KalicoCrew/kalico/pull/47/files#diff-7a6e8eb4ab74dc0c3707b9e39a09bbb8376247587fdb6fe5c02c88dbb38b0ec8R354) removes the second derivative. This again probably stems from confusing this with motor control.



In practise, all this controller adds is a rudimentary anti-windup (which could have been [added](https://github.com/KalicoCrew/kalico/pull/47#issuecomment-2585564583) in normal PID form as well). This is nice, but not well communicated.

Instead there is this false claim:
> [In some scenarios](https://github.com/KalicoCrew/kalico/blame/a6b7a38189e89e1df84b061ebc0c0f06dee5d1df/docs/PID.md#L188-L191) Velocity control will also be better at holding the heater at its target temperature, and rejecting disturbances. > The primary reason for this is that velocity control is more like a standard second order differential equation. It takes into account position, velocity, and acceleration.

Aside from filtering you added, mathematically both PID forms are the same. This sounds like misinterpretation of https://www.controleng.com/articles/the-velocity-of-pid/ . 

Oh indeed @dans98, seems that companies like [Rockwell](https://literature.rockwellautomation.com/idc/groups/literature/documents/wp/logix-wp008_-en-p.pdf) call this a Velocity Form and explain well the benefits of the implementation. 

But I think in the software like this a single implementation is enough and the end user should not care.

Instead of switching between implementations, the user could just have a choice to "Saturate integral term". 

Also "Derivative kick" prevention on [P term](https://github.com/KalicoCrew/kalico/pull/47/files#diff-7a6e8eb4ab74dc0c3707b9e39a09bbb8376247587fdb6fe5c02c88dbb38b0ec8R331) doesn't make sense for the heater control and I think it should be removed for the faster response. 

Just my 2cents.
Feel free to point out any inaccuracies.

**Pull request merged**
