### PR TITLE
Implemented a way to ignore PROBE_POINTS_INCREASING

### PR DESCRIPTION
**Pull request by Zeanon**
Someone mentioned this feature in the DK Discord channel

### CODE REVIEW

**Comment by lraithel15133** [comment]
I think I would prefer to see a configurable threshold. I haven't looked at the code myself, though.

**Comment by Zeanon** [comment]
I have an idea for the threshhold, let me try
I'll make a seperate branch for the threshold and link it here so it can be tried out but doesnt clutter the current PR

**Comment by Zeanon** [comment]
@lraithel15133 take a look in here:
https://github.com/Zeanon/danger-klipper/tree/increasing_threshold

**Comment by rogerlz** [comment]
I like the idea with a threshold

**Comment by Zeanon** [comment]
new pr is open with adjustable threshold: https://github.com/DangerKlippers/danger-klipper/pull/189

**Comment by rogerlz** [comment]
closing this one then

**Pull request closed without merging**
