### PR TITLE
Add Dan98's positional PID algorithm

### PR DESCRIPTION
**Pull request by jslaker**
This PR adds @Dans98 's Positional PID algorithm updated with support for PID profiles to DangerKlipper. This code was originally part of Klipper3d/klipper#5955 along with pid_v and the new calibration routine, but was removed from the subsequent PRs that were merged into DK.

This algorithm functions largely the same as the standard PID loop from mainline Klipper, but corrects a few fundamental implementation errors that cause temperature overshoot and instability on some setups. 

Because this change is high impact/risk in nature, I've implemented this as an additional ControlPositionalPID heater class instead of replacing the mainline loop outright. The core PID algorithm has nearly two years of testing behind it at this point and should be solid, but it'd probably be wise to allow an extended testing period to make sure my changes to add in PID profiles haven't caused any side effects before/if the current loop is replaced.

Users can select this algorithm by setting `control = pid_p`.

### CODE REVIEW

**Comment by CroXY3D** [comment]
It should be called pid_p not positional for consistency and clarity that it is a pid control

**Comment by jslaker** [comment]
Agreed -- just pushed a commit making that change.

**Comment by rogerlz** [comment]
I always favour optional features that users can decide whether to use or not.

would you please add it to the config reference, readme, and cover it with some testing? ping me on discord if needed

**Comment by dans98** [comment]
fyi i just wanted to check in say I haven't had time to look at this yet, as I came down with a case of the flue that almost put me in the hospital.

**Comment by jslaker** [comment]
Had a couple of minutes to add documentation to this. 

I haven't had a chance to review the proposed changes from @Zeanon (but also haven't forgotten about it!) I'll likely hold off until Dan is feeling well enough to get an additional set of eyes on it.

@rogerlz -- I'll ping you at some point to work out what would make sense for test coverage. 

(I've also corrected the black errors on my local copy but am holding off on committing so I don't clog up the commit timeline with formatting changes).

**Comment by rogerlz** [comment]
@jslaker I formatted the code and added some basic tests just to make sure the module loads with the new parameter

**Comment by dans98** [comment]
@jslaker 

I'm still not back to 100%, But I'm good enough to look at the code.  I made a few changes to your class and have attached it. However I wasn't able to test it as I'm out of town and will be for a while. 

Notes:
1) we can't use heater.pwm_delay as a constant, because as you might remember Kevin said nothing guarantees consistent timing. Thus, I altered the code to keep track of the previous read time and calculate the time delta with each step. _dt = read_time - self.prev_temp_time_

2) I updated the derivative smoothing to be inline with the above and used the same smoothing algorithm i did for pid_v 



[updated.txt](https://github.com/DangerKlippers/danger-klipper/files/15083655/updated.txt)

**Comment by Zeanon** [comment]
just a small fyi, profile switching will work with the current implementation but it wont be as smooth, I'll let you guys figure out how to handle all the different stuff and then after that's final, I'll add stuff to load the proper initial values

**Review by bwnance — CHANGES_REQUESTED** [review]
just marking as changes requested post-dan's review (a few comments above)

**Comment by rogerlz** [comment]
This PR seems abandoned for a while, so I am closing it but feel free to reopen or open a new one to continue working on the feature.

**Comment by jslaker** [comment]
@rogerlz - I agree with this decision. Unfortunately, I haven't had the bandwidth recently to revisit this. Work has successfully kept me mentally exhausted of late -- I won't be offended if anyone else chooses to pick this up. :) 

The core PID controller should be largely good to go, but I suspect the parts touching PID profiles in particular would need an overhaul at this point to get it into a shippable state. With MPC now merged, the primary value here is going to be for bed heaters.

**Pull request closed without merging**
