### PR TITLE
fixes for good sensorless

### PR DESCRIPTION
**Pull request by bwnance**

### CODE REVIEW

**Comment by bwnance** [comment]
@nielsvz if you have a second, please test this!

**Comment by nielsvz** [comment]
> @nielsvz if you have a second, please test this!

I tested the proposed changes with the following settings:
```ini
[tmc5160 stepper_x]
current_change_dwell_time: 2.0
home_current: 2.0
run_current: 2.8

[stepper_x]
homing_positive_dir: True
homing_retract_dist: 5
homing_retract_speed: 20
homing_speed: 100
min_home_dist: 40
second_homing_speed: 100
use_sensorless_homing: True
```

Looks like this works 👍 
* toolhead further away then `min_home_dist`: the axis homes, then backs off to `homing_retract_dist`.
* toolhead closer to the endstop position then `min_home_dist`: axis homes, backs off to `min_home_dist`, homes again and backs off to `homing_retract_dist`.

**Comment by bwnance** [comment]
@nielsvz awesome, thank you!

**Review by rogerlz — DISMISSED** [review]
:chefkiss:

**Comment by rogerlz** [comment]
> Awesome, any plan to merge this in master branch ?

yes, I am doing some final tests this week and it should be merged soon

**Review by rogerlz — APPROVED** [review]

**Pull request merged**
