### PR TITLE
Dual loop pid

### PR DESCRIPTION
**Pull request by rodrigo2019**
upstream: https://github.com/Klipper3d/klipper/pull/5972
got some @rogerlz implementation from https://github.com/DangerKlippers/danger-klipper/pull/58 and fixed merge issues with the pid_v features

### CODE REVIEW

**Comment by CarVac** [comment]
Might it be better called "cascade PID" to match standard terminology?

https://en.wikipedia.org/wiki/Proportional%E2%80%93integral%E2%80%93derivative_controller#Cascade_control

**Comment by rodrigo2019** [comment]
> Might it be better called "cascade PID" to match standard terminology?
> 
> https://en.wikipedia.org/wiki/Proportional%E2%80%93integral%E2%80%93derivative_controller#Cascade_control

Cascade PID is different from this one, cascade PID involves a hierarchical arrangement where one PID loop sets the setpoint for another. In this case we have two parallel pid's and the final signal its a minimum value between both.

**Comment by CarVac** [comment]
Ah, I see. Never mind then.

**Comment by Kishmeth** [comment]
Still seems to break pid_v (however I'm on the bleeding edge branch so might be some changes there)

No other issues, smooth control even with a 12kg thermal mass.

**Comment by rogerlz** [comment]
I am testing this PR this week

**Comment by fn2dk** [comment]
i can really see the benefit of this used in a " active chamber" ! .

**Comment by Nathan22211** [comment]
I get config wrapper errors trying to bring this into bleeding edge for testing, did bleeding edge even touch the heater's code?

**Comment by bwnance** [comment]
We seem to be having a weird GitHub bug that is auto-closing this PR

**Comment by bwnance** [comment]
maybe it'll work with a comment?

**Comment by rodrigo2019** [comment]
virtual bullying

**Comment by Nathan22211** [comment]
Wtf is going on with this PR my email has been spammed periodically most of
the day

**Comment by Cellivar** [comment]
You're hitting a corner case in how GitHub PRs work. It looks like this repo is no longer a fork of Klipper, it's a separate repo. This PR was opened before that, when rodrigo2019's repo and this repo were both forks of Klipper. 

When this repo was disconnected the PR was automatically closed, GitHub can't handle PRs between repos that aren't in the same network anymore. 

There is no way to fix this PR, a new one will need to be opened from a fork of danger-klipper.

**Pull request closed without merging**
