### PR TITLE
SD card file list sorting in menu

### PR DESCRIPTION
**Pull request by MarSoft**
This is an adaptation of https://github.com/Klipper3d/klipper/pull/6589 for this code base. It adds an option to sort files in `vsdlist` menu on the display by their modification time, so that freshly uploaded files are shown first.

## Checklist

- [x] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

### CODE REVIEW

**Comment by kageurufu** [comment]
I don't like returning the three-tuple, I have a different approach to do the same for my #364 (i haven't pushed it), returning `tuple[str, os.stat_result]`

os.path.getsize and os.path.getmtime both do os.stat and return the relevant field, so I strongly prefer doing that (one less system call) 

I added a review to the upstream PR noting that as well.

**Review by rogerlz — CHANGES_REQUESTED** [review]
discussion is still happening in https://github.com/Klipper3d/klipper/pull/6589

**Comment by kageurufu** [comment]
fwiw, I have at this point replaced `vsdlist` in #364

it doesn't used sdcard.get_file_list at all, so it can do proper path traversal

**Comment by rogerlz** [comment]
I believe the original desire has been achieved with #364, so I am closing this one. Feel free to reopen if my understanding is wrong.

**Pull request closed without merging**
