### PR TITLE
shaper_calibrate: store accel_per_hz

### PR DESCRIPTION
**Pull request by rogerlz**
https://github.com/DangerKlippers/danger-klipper/issues/221

image

## Checklist

- [x] pr title makes sense
- [x] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [x] ci is happy and green

### CODE REVIEW

**Comment by Frix-x** [comment]
Hello,

Good initiative, I kind of tweaked something in Shake&Tune to print it on the header as well, but I much prefer to get a proper access like you've done.

As a side note, this will probably break current Shake&Tune with DangerKlipper until a fix is done on my side to account for the changes in the CSV, etc...

**Comment by rogerlz** [comment]
> Hello,
> 
> Good initiative, I kind of tweaked something in Shake&Tune to print it on the header as well, but I much prefer to get a proper access like you've done.
> 
> As a side note, this will probably break current Shake&Tune with DangerKlipper until a fix is done on my side to account for the changes in the CSV, etc...

would it help if I make it a parameter default to False?

**Review by bwnance — APPROVED** [review]

**Comment by Frix-x** [comment]
As discussed with bwnance on Discord, I don't think adding another parameter is needed: I don't want to add even more complexity to this.

I'll try to account for it and auto-detect the CSV file format directly :)

**Comment by rogerlz** [comment]
> As discussed with bwnance on Discord, I don't think adding another parameter is needed: I don't want to add even more complexity to this.
> 
> I'll try to account for it and auto-detect the CSV file format directly :)

great! we will hold off merging this until you are ready.

**Comment by Frix-x** [comment]
I think since it doesn't block the use of the default script, you can merge it now.
I don't want to block it just for Shake&Tune compatibility, since it's not problematic and works on its own with the original Klipper tools that are still available. But I'll try to fix the compatibility as soon as possible.

**Pull request merged**
