### PR TITLE
Firmware retraction fix and extends zhop features.

### PR DESCRIPTION
**Pull request by fbeauKmi**
As discuss on Discord, DK firmware and according to issue https://github.com/DangerKlippers/danger-klipper/issues/204 and PR https://github.com/DangerKlippers/danger-klipper/pull/206 . I made this for a while some change to fit my use case. I guess it can fix the issue.

Changes from actual firmware_retraction 
- introduces `reset_on_events` parameter. (false : keep retracted state on events, true: reset retracted state and restore config values). 
- Ability to use `SET_RETRACTION` while retracted
- Ability to do zhop even if retract_length=0.0
- Always do zhop as relative moves

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [x] added a test case if possible
- [x] if new feature, added to the readme
- [ ] ci is happy and green

### CODE REVIEW

**Comment by richfelker** [comment]
I've been testing this and it works for me except that it still produces warning spam on G10 and G11 commands that should be idempotent. This messes up the start of every print, where the start gcode needs to have left the extruder in retracted state, but Cura also emits its own retraction for the first travel move. Supporting this kind of idempotency instead of double-retracting and messing up priming is, from my perspective, one of the compelling motivations for firmware retract in the first place, so it should not be treated as something abnormal that produces warnings.

As discussed on Discord, I would also like to see the issue resolved in a way that makes it possible to use Z-hop and get the right properties for how fw retract is supposed to work. This probably means something like having it so entering retracted state lifts Z by the configured amount, but explicitly moving in Z after that loses the offset and moves to the actual commanded Z height, and so that exiting retracted state only returns to the logical, non-offset Z height (doing nothing if Z was moved since the retract).

**Comment by fbeauKmi** [comment]
> I've been testing this and it works for me except that it still produces warning spam on G10 and G11 commands that should be idempotent. This messes up the start of every print, where the start gcode needs to have left the extruder in retracted state, but Cura also emits its own retraction for the first travel move. Supporting this kind of idempotency instead of double-retracting and messing up priming is, from my perspective, one of the compelling motivations for firmware retract in the first place, so it should not be treated as something abnormal that produces warnings.

I removed the console outputs
> 
> As discussed on Discord, I would also like to see the issue resolved in a way that makes it possible to use Z-hop and get the right properties for how fw retract is supposed to work. This probably means something like having it so entering retracted state lifts Z by the configured amount, but explicitly moving in Z after that loses the offset and moves to the actual commanded Z height, and so that exiting retracted state only returns to the logical, non-offset Z height (doing nothing if Z was moved since the retract).

This point doesn't fit my workflow but I think we can do something configurable, for example a boolean ``clear_zhop_on_z_moves`` parameter to let the user choose. Unclear to me , does this apply to relative and absolute movements?

**Comment by rogerlz** [comment]
@fbeauKmi would you mind rebasing? ty

**Comment by fbeauKmi** [comment]
> @fbeauKmi this looks good to me.. would you mind rebasing? ty

@rogerlz If you don't mind, I'd like to wait for feedback before merging.  I'm not sure clear_zhop feature is useful for relative moves. TY

**Comment by pdscomp** [comment]
HI all! Did some banging on this PR, here are the things I tried and my feedback. Hopefully this is helpful!

Initial conditions:
* Switched from DangerKlipper main branch to pr 211
* Re-started klipper and mainsail services
* Checked klippy.log to ensure correct version/checkout of Klipper was running
	Starting Klippy...
	Args: ['/home/paul/klipper/klippy/klippy.py', '/home/paul/printer_data/config/printer.cfg', '-I', '/home/paul/printer_data/comms/klippy.serial', '-l', '/home/paul/printer_data/logs/klippy.log', '-a', '/home/paul/printer_data/comms/klippy.sock']
	App Name: Danger-Klipper
	Git version: 'v0.12.0-459-gd3a8180ad'
	Branch: firmware_retract
	Remote: https://github.com/fbeauKmi/danger-klipper.git
* Configured new firmware retraction settings with z_hop_heights=1mm and reset_on_events=true:
	[firmware_retraction]
	# The length of filament (in mm) to retract when G10 is activated,
	# and to unretract when G11 is activated (but see
	# unretract_extra_length below). The default is 0 mm.
	retract_length: 0.6
	# The speed of retraction, in mm/s. The default is 20 mm/s.
	retract_speed: 35
	# The length (in mm) of *additional* filament to add when
	# unretracting.
	unretract_extra_length: 0
	# The speed of unretraction, in mm/s. The default is 10 mm/s.
	unretract_speed: 35
	# Height of nozzle lifting move (Z-Hop). The default is 0 mm.
	#z_hop_height: 0.2
	# Set to default of 1.0 for testing (easy to spot working as-expected)
	z_hop_height: 1.0
	# DangerKlipper PR #211: Reset retraction to default on
	# CLEAR_RETRACTION, homing, motor_off, start print and end print
	# from virtual sdcard. Retracted state is set to False.
	reset_on_events: True
* Good to go!

Test #1:
* Performed normal print with Slicer-managed retraction
Result: PASS
* Print succeeded as-expected with no issues

Test #2:
* Add new z_hop_height parameter to printer.cfg and restart klipper:
[firmware_retraction]
…
	# Height of nozzle lifting move (Z-Hop). The default is 0 mm.
	z_hop_height: 1
Result: PASS
* Klipper accepted the new parameter and loaded/started correctly

Test #3:
* Tried out new GET_RETRACTION GCode without any overrides:
Result: PASS
* Worked as expected:
	22:06:51 $ GET_RETRACTION
	22:06:51 // RETRACT_LENGTH=0.60000 RETRACT_SPEED=35.00000 UNRETRACT_EXTRA_LENGTH=0.00000 UNRETRACT_SPEED=35.00000  Z_HOP_HEIGHT=1.00000  RETRACTED=False

Test #4a:
* Override Z-Hop Height via new SET_RETRACTION Gcode:
	21:42:29 $ SET_RETRACTION z_hop_height=0.4
* Check to make sure value was set correctly in the Klipper state:
	21:42:34 $ GET_RETRACTION
	21:42:34 // RETRACT_LENGTH=0.60000 RETRACT_SPEED=35.00000 UNRETRACT_EXTRA_LENGTH=0.00000 UNRETRACT_SPEED=35.00000  Z_HOP_HEIGHT=0.40000  RETRACTED=False
Result: PASS
* Value was stored correctly and looks good

Test #4b:
*  Attempt to use new CLEAR_RETRACTION to reset all retraction settings back to stock printer config after running above test to override it from the default (1mm) to 0.4mm
	21:42:43 $ CLEAR_RETRACTION
	21:42:43 // WARNING: Printer is not retracted. Command has been ignored!
Result: FAIL
* It appears that the CLEAR_RETRACTION GCode command is only accepted when the firmware believes the nozzle is in a "retracted" state (i.e. RETRACTED=True)
* As per documentation (original and updated in this PR):
	CLEAR_RETRACTION: Clears the current retract state without extruder or motion system movement. All flags related to the retract state are reset to False and all changes to retraction parameters made via previous SET_RETRACTION commands are reset to config values. 
	From <https://dangerklipper.io/G-Codes.html?h=z_hop_height#firmware_retraction> 
	CLEAR_RETRACTION: Clears the current retract state without extruder or motion system movement. All flags related to the retract state are reset to False. If reset_on_events is set to True, all changes to retraction parameters made via previous SET_RETRACTION commands are reset to config values.
	From <https://github.com/DangerKlippers/danger-klipper/blob/d3a8180adac8f06491bc51c7ce7a20206ca0e05f/docs/G-Codes.md> 
* It makes sense that it wouldn't need to change RETRACTED back to False since we were not retracted in this case
* Based on the documentation and intended usage however I would still expect this command to reset all of the values back to default from config file (RETRACT_LENGTH, RETRACT_SPEED, UNRETRACT_EXTRA_LENGTH, UNRETRACT_SPEED, and Z_HOP_HEIGHT).
* Issue that should probably be addressed?
Expected Behavior:
* As-documented, CLEAR_RETRACTION should reset all variables to config defaults even when RETRACTED is currently False.
* Recommendation to separate out CLEAR_RETRACTION and RESET_RETRACTION as two separate gcode commands are captured in final notes at the bottom.

Test 5:
* Testing override of Z-Hop for a specific filament in OrcaSlicer, and restore default settings after print
* Edit Filament settings -> Advanced -> Filament start G-code:
	; filament start gcode
	; Usage: SET_RETRACTION RETRACT_LENGTH=<mm> RETRACT_SPEED=<mm/s> UNRETRACT_EXTRA_LENGTH=<mm> UNRETRACT_SPEED=<mm/s> Z_HOP_HEIGHT=<mm>
	M118 Overriding default Z-Hop for DuramiC PETG, setting to 0.4
	SET_RETRACTION z_hop_height=0.4
	GET_RETRACTION
* Edit filament settings -> Advanced -> Filament end G-code:
	; filament end gcode 
	M118 Clearing retraction override settings, going back to Klipper defaults from config
	CLEAR_RETRACTION
	GET_RETRACTION
Result: PARTIAL FAIL
* The first part of this works great! The override happens at the start of print, and takes effect (can see from GET_RETRACTION echo as well as behavior of the printer going from 1.0 to 0.4 retraction when printing)
* The CLEAR fails to restore default settings after the print (same as in the above test)
	22:33:50 $ GET_RETRACTION
	22:33:51 // RETRACT_LENGTH=0.60000 RETRACT_SPEED=35.00000 UNRETRACT_EXTRA_LENGTH=0.00000 UNRETRACT_SPEED=35.00000  Z_HOP_HEIGHT=0.40000 RETRACTED=False
	22:34:04 $ CLEAR_RETRACTION
	22:34:04 // WARNING: Printer is not retracted. Command has been ignored!
	22:34:05 $ GET_RETRACTION
	22:34:05 // RETRACT_LENGTH=0.60000 RETRACT_SPEED=35.00000 UNRETRACT_EXTRA_LENGTH=0.00000 UNRETRACT_SPEED=35.00000  Z_HOP_HEIGHT=0.40000 RETRACTED=False
* I believe this is a good representative example of how this would be used for folks doing Firmware retraction for 99% of cases but want to tweak certain retraction parameters on a per-filament basis, and then restore the default after a print is complete

Test 6a:
* I was able to force a CLEAR_RETRACTION to occur while retraction was happening (by setting a ridiculously high Z_HOP value)
	22:36:54  $ GET_RETRACTION
	22:36:54 // RETRACT_LENGTH=0.60000 RETRACT_SPEED=35.00000 UNRETRACT_EXTRA_LENGTH=0.00000 UNRETRACT_SPEED=35.00000  Z_HOP_HEIGHT=5.00000  RETRACTED=False
	22:36:56 $ CLEAR_RETRACTION
	22:36:57 // Retraction was cleared. zhop is undone on next move.
	22:36:58 $ GET_RETRACTION
	22:36:58 // RETRACT_LENGTH=0.60000 RETRACT_SPEED=35.00000 UNRETRACT_EXTRA_LENGTH=0.00000 UNRETRACT_SPEED=35.00000  Z_HOP_HEIGHT=5.00000  RETRACTED=False
Result: SUCCESS
* It looks like it did clear the RETRACTED flag and successfully undo the retraction as part of the next move (the benchy I was printing was not mangled by the change)
* With reset_on_events being true, it looks like it also restored the default z_hop_height for the rest of this print.

Test 6b:
* Re-run of test 6b but changing reset_on_events to false
Result: SUCCESS with comment
* It did clear the RETRACTED flag successfully, and successfully undo the retraction as part of the next move (the benchy I was printing was not mangled by the change)
* This did not affect the z_hop_height (resetting to defaults) which I believe is expected based on the documented behavior of reset_on_events.

* However the Z_HOP_HEIGHT was not successfully restored to defaults
* It looks like even when CLEAR_RETRACTION is running, it's skipping the step to reset all the values to default or is only resetting some of them and not Z_HOP_HEIGHT?

Test 7:
* Documentation Review
* All commands and command parameters must be documented in G-Codes.md.
	Additional documentation present in G-Codes!
* All user facing modules and their config parameters must be documented in Config_Reference.md.
	Additional param for [firmware_retraction] documented in Config_Reference
* All exported "status variables" must be documented in Status_Reference.md.
	Status variable addition is documented here
* All new "webhooks" and their parameters must be documented in API_Server.md.
	N/A or didn't see anything relevant?
* Any change that makes a non-backwards compatible change to a command or config file setting must be documented in Config_Changes.md.
	N/A or didn't see anything relevant?
Result: QUERY
* Not sure if this is an issue or not (or just possibly a discrepancy) however GET_RETRACTION shows the i-am-currently-retracted-status as RETRACTED with a True/False value
* The Status_Reference.md refers to this same value as:
	retract_state: Returns 'True' if filament is retracted.

Test 8:
* Couldn't figure out a good way to test this parameter--in theory Z moves should never be commanded while in retracted state, anything done here would have to be contrived? Seems like this is an error case that this is defining how to handle? Might be misunderstanding purpose of this.
	#clear_zhop_on_z_moves: False
	#   If True, in absolute movements, when a command in Z is sent while toolhead
	#   is retracted, z_hop is cancelled until next retraction. Otherwise,
	#   `z_hop_height` is applied as an offset to all movements.


Final Commentary:
As someone who is very interested in this feature, I think this implementation is EXTREMELY close to what would make sense for 99% of folks who want to use FIRMWARE_RETRACTION in conjunction w/ z-hop and dynamically tuning retraction settings!

Recommendations prior to merge/release:
1. Create new RESET_RETRACTION GCODE function (suggested description for documentation):
	`RESET_RETRACTION`: All changes to retraction parameters made via previous SET_RETRACTION commands are reset to config values.
	NOTE: It is recommended to add `RESET_RETRACTION` to your start and end gcode
	(with a possible override in your filament start gcode to set filament-specific overrides
	of firmware retraction defaults via `SET_RETRACTION`).
	
	* This is something I could see myself using often when manually jamming in test values to go back to config values, would work anytime, and would not be affected by the current retract_state or RETRACTED
2. Normalize naming convention to either retract_state or RETRACTED (slightly confusing to have both but they are the same thing)

3. Update documentation and behavior of CLEAR_RETRACTION:
	`CLEAR_RETRACTION`: Clears the current retract state without extruder or
	motion system movement.
	NOTE: The Module contains a lot of redundancy for safety to prevent undesired
	behavior. When printing from virtual SD Card, in retracted state, the printer
	state is monitored and zhop moves are cancelled if a print is started, canceled
	or finished or if a virtual SD card file is reset until next unretract. When
	printing via GCode streaming (e.g. using OctoPrint), the zhop moves are
	cancelled when the steppers are disabled (M84, typically part of end gcode and
	standard behavior of OctoPrint if a print is canceled) or the printer is homed
	(G28, typically part of start gcode). Hence,
	upon ending or canceling a print as well as starting a new print via GCode
	streaming or virtual SD card, the toolhead will not apply `z_hop_height` until
	next G11 if filament is retracted.
	Nevertheless, it is recommended to add `CLEAR_RETRACTION` to your start and end
	gcode to make sure the retract state is reset before and after each print.
	
	* CLEAR_RETRACTION would then function as it currently does when RESET_ON_EVENTS is false

4. Update documentation and behavior of RESET_ON_EVENTS to match the above:
	reset_on_events: False
	    While False, Klipper leaves managing retraction overrides up to the user/macros/slicer gcode.
	    While True, Klipper automatically issues a `CLEAR_RETRACTION` and `RESET_RETRACTION`, 
	    resetting firmware retraction parameters to config values and current
	    retract_state to False, triggered by the following activities:
        homing, motor_off, start print, and end print from virtual sdcard.

**Comment by fbeauKmi** [comment]
> HI all! Did some banging on this PR, here are the things I tried and my feedback. Hopefully this is helpful!

First, big thanks for this review,  Sure it is helpful. If you don't mind i will only comment the "failed" tests.

> Test #4b:
> *  Attempt to use new CLEAR_RETRACTION to reset all retraction settings back to stock printer config after running above test to override it from the default (1mm) to 0.4mm
> 	21:42:43 $ CLEAR_RETRACTION
> 	21:42:43 // WARNING: Printer is not retracted. Command has been ignored!
> Result: FAIL
> * It appears that the CLEAR_RETRACTION GCode command is only accepted when the firmware believes the nozzle is in a "retracted" state (i.e. RETRACTED=True)
> * As per documentation (original and updated in this PR):
> 	CLEAR_RETRACTION: Clears the current retract state without extruder or motion system movement. All flags related to the retract state are reset to False and all changes to retraction parameters made via previous SET_RETRACTION commands are reset to config values. 
> 	From <https://dangerklipper.io/G-Codes.html?h=z_hop_height#firmware_retraction> 
> 	CLEAR_RETRACTION: Clears the current retract state without extruder or motion system movement. All flags related to the retract state are reset to False. If reset_on_events is set to True, all changes to retraction parameters made via previous SET_RETRACTION commands are reset to config values.
> 	From <https://github.com/DangerKlippers/danger-klipper/blob/d3a8180adac8f06491bc51c7ce7a20206ca0e05f/docs/G-Codes.md> 
> * It makes sense that it wouldn't need to change RETRACTED back to False since we were not retracted in this case
> * Based on the documentation and intended usage however I would still expect this command to reset all of the values back to default from config file (RETRACT_LENGTH, RETRACT_SPEED, UNRETRACT_EXTRA_LENGTH, UNRETRACT_SPEED, and Z_HOP_HEIGHT).
> * Issue that should probably be addressed?
> Expected Behavior:
> * As-documented, CLEAR_RETRACTION should reset all variables to config defaults even when RETRACTED is currently False.
> * Recommendation to separate out CLEAR_RETRACTION and RESET_RETRACTION as two separate gcode commands are captured in final notes at the bottom.
> 
> Test 5:
> Result: PARTIAL FAIL

Good point, there's no reason to disable CLEAR_RETRACTION when not retracted. I agree 100% with your proposal to separate the functions (CLEAR_RETRACTION to set the retracted state to false, RESET_RETRACTION to recall the configuration defaults, although I think SET_RETRACTION is sufficient to call the parameters at the start of printing) Nevertheless, this introduces a **break change** on CLEAR_RETRACTION. I don't know how many users test this function or how they use CLEAR_RETRACTION. @rogerlz What do you think? Am I allowed to make this change? 


> Test 6b:
> * Re-run of test 6b but changing reset_on_events to false
> Result: SUCCESS with comment
> * It did clear the RETRACTED flag successfully, and successfully undo the retraction as part of the next move (the benchy I was printing was not mangled by the change)
> * This did not affect the z_hop_height (resetting to defaults) which I believe is expected based on the documented behavior of reset_on_events.
> 
> * However the Z_HOP_HEIGHT was not successfully restored to defaults
> * It looks like even when CLEAR_RETRACTION is running, it's skipping the step to reset all the values to default or is only resetting some of them and not Z_HOP_HEIGHT?

Documentation is probably unclear on this. The current PR behavior is : When `reset_on_events` is set to `false` , events will only  clear actual zhop to avoid collision. CLEAR_RETRACTION only reset retract_state. That's why your suggestion above makes sense.
Use case example:
```
G10 #toolhead retraction + zhop : 
G28 #homing (reset all axes to origin), clear zhop
G1 X150 Y150 Z0.2 F18000 #move to start point 
G11 #untretract/ Zhop was clear to avoid bed collision
``` 

> 
> Test 7:
> * Documentation Review
> Result: QUERY
> * Not sure if this is an issue or not (or just possibly a discrepancy) however GET_RETRACTION shows the i-am-currently-retracted-status as RETRACTED with a True/False value
> * The Status_Reference.md refers to this same value as:
> 	retract_state: Returns 'True' if filament is retracted.

I have no opinion on this point. `retract_state` is an element that can be called by a macro or plugin. If something needs to be changed, it's RETRACTED, which is the console output. 

> 
> Test 8:
> * Couldn't figure out a good way to test this parameter--in theory Z moves should never be commanded while in retracted state, anything done here would have to be contrived? Seems like this is an error case that this is defining how to handle? Might be misunderstanding purpose of this.
> 	```
> 	#clear_zhop_on_z_moves: False
> 	#   If True, in absolute movements, when a command in Z is sent while toolhead
> 	#   is retracted, z_hop is cancelled until next retraction. Otherwise,
> 	#   `z_hop_height` is applied as an offset to all movements.```

There's several use cases where toolhead moves in Z while retracted ( layer change, toolchanger, filament change, ...). This point was added to answer a previous comment https://github.com/DangerKlippers/danger-klipper/pull/211#issuecomment-2185343413
This feature is to keep offset if a Z move is ordered or to move the toolhead to the requested Z canceling Zhop

> 
> Final Commentary:
> As someone who is very interested in this feature, I think this implementation is EXTREMELY close to what would make sense for 99% of folks who want to use FIRMWARE_RETRACTION in conjunction w/ z-hop and dynamically tuning retraction settings!
> 
> Recommendations prior to merge/release:
> 1. Create new RESET_RETRACTION GCODE function (suggested description for documentation):
> 	`RESET_RETRACTION`: All changes to retraction parameters made via previous SET_RETRACTION commands are reset to config values.
> 	NOTE: It is recommended to add `RESET_RETRACTION` to your start and end gcode
> 	(with a possible override in your filament start gcode to set filament-specific overrides
> 	of firmware retraction defaults via `SET_RETRACTION`).
> 	
> 	* This is something I could see myself using often when manually jamming in test values to go back to config values, would work anytime, and would not be affected by the current retract_state or RETRACTED
> 2. Normalize naming convention to either retract_state or RETRACTED (slightly confusing to have both but they are the same thing)
> 
> 3. Update documentation and behavior of CLEAR_RETRACTION:
> 	`CLEAR_RETRACTION`: Clears the current retract state without extruder or
> 	motion system movement.
> 	NOTE: The Module contains a lot of redundancy for safety to prevent undesired
> 	behavior. When printing from virtual SD Card, in retracted state, the printer
> 	state is monitored and zhop moves are cancelled if a print is started, canceled
> 	or finished or if a virtual SD card file is reset until next unretract. When
> 	printing via GCode streaming (e.g. using OctoPrint), the zhop moves are
> 	cancelled when the steppers are disabled (M84, typically part of end gcode and
> 	standard behavior of OctoPrint if a print is canceled) or the printer is homed
> 	(G28, typically part of start gcode). Hence,
> 	upon ending or canceling a print as well as starting a new print via GCode
> 	streaming or virtual SD card, the toolhead will not apply `z_hop_height` until
> 	next G11 if filament is retracted.
> 	Nevertheless, it is recommended to add `CLEAR_RETRACTION` to your start and end
> 	gcode to make sure the retract state is reset before and after each print.
> 	
> 	* CLEAR_RETRACTION would then function as it currently does when RESET_ON_EVENTS is false
> 
> 4. Update documentation and behavior of RESET_ON_EVENTS to match the above:
> 	reset_on_events: False
> 	    While False, Klipper leaves managing retraction overrides up to the user/macros/slicer gcode.
> 	    While True, Klipper automatically issues a `CLEAR_RETRACTION` and `RESET_RETRACTION`, 
> 	    resetting firmware retraction parameters to config values and current
> 	    retract_state to False, triggered by the following activities:
>         homing, motor_off, start print, and end print from virtual sdcard.
> ```

I hope I've answered all the points. Once again, thank you for your time.

**Comment by pdscomp** [comment]
@fbeauKmi happy to help! Also wanted to report back that I've been running this PR branch for the last 2+ weeks, and everything has been working very well from a printing perspective using exclusively firmware retraction (with or without z-hop--I've been tuning that in the Filament Start and Stop gcode!)

For now I have this in my slicer GCode for filament-specific start and stop to override for example PETG which tends to be a bit more leaky for me than PLA since I run it hot (and 0.6 matches what was in my config file as a default):
```
; filament start gcode
; Configure Firmware Retraction Override
SET_RETRACTION retract_length=0.8 z_hop_height=0

; filament end gcode 
; Reset retraction to default
SET_RETRACTION retract_length=0.6 z_hop_height=0
```
I would replace the second block with just ```RESET_RETRACTION``` which also means I wouldn't have to hardcode a value in my slicer that hopefully matches what I set in the Klipper config. I have the z_hop_height in as a parameter, have been toying with leaving it off by default and then only turning it on / tweaking it on a per-filament basis (which I think some of the folks in the DK chat recommended!)

Thanks for all your hard work on this, I'm happy to test a new version or help with docs/review as-needed! Cheers.

**Comment by fbeauKmi** [comment]
Hello,  I've completely rewritten the module to get rid of the multiple safety tests and try to answer the previous comments. I should probably close this PR and open a new one to clean up the commits history. The code proposal diverges from the current firmware_retraction .
Current changes vs old version
- no G0/G1 overrides. the zhop is applied as an offset, it does not affect gcode position (solve an issue with pause/resume) 
- add `clear_zhop_on_z_moves` parameter . Allow to  clear zhop if a move in z is requested when toolhead is retracted 
- CLEAR_RETRACTION doesn't reset parameters to default. RESET_RETRACTION is added to do that.
- add `zhop_state`, independent of `retract_state` 
- no automatic reset of `retract_state`  and parameters on events (home, print_start, print_end). Only zhop is reset on home/stepper off.

**Comment by richfelker** [comment]
These changes sound good. One really exciting thing with making zhop an offset is that you should be able to do it as an offset-wthout-move (like `SET_GCODE_OFFSET MOVE=0` does). This would make it so that the motion in Z happens concurrent with the next move rather than as its own discrete move, making it much faster and giving less chance of stringing.

**Comment by pdscomp** [comment]
This looks awesome! Will pull down the latest and start running the updates as my daily driver.

**Comment by rogerlz** [comment]
@fbeauKmi should I close this one and wait for the new one? 🚀

**Comment by fbeauKmi** [comment]
I don't have much time to work on it at the moment. I'll open a cleaner PR soon <sup>tm</sup>
Thanks.

**Pull request closed without merging**
