### PR TITLE
Add belay module

### PR DESCRIPTION
**Pull request by rsghosh**
This adds the `belay` module from the [Annex Belay repo](https://github.com/Annex-Engineering/Belay) and copies related documentation into the following documents:
- Config_Reference
- G-Codes
- Status_Reference

### CODE REVIEW

**Comment by rogerlz** [comment]
@rsghosh yay! nice seeing this coming to DK.

Would you please format the code? We use black and flake8, also there is a pre-commit config for convenience.

**Comment by rsghosh** [comment]
Sounds good. Just now I formatted the code with black and checked it with pre-commit.

**Review by rogerlz — APPROVED** [review]

**Comment by rogerlz** [comment]
lgtm and thanks!
feel free to PR something to the README documenting that belay/tradrack modules are part of the features
also feel free to take advantage of the automated tests under test/klippy

**Comment by rsghosh** [comment]
Thanks! I'll look into adding tests and updating the README

**Pull request merged**
